name: Terraform development pipeline

permissions:
  contents: read
  pull-requests: write
  id-token: write
  
on:
  # Todo: Remove branch trigger
  push:
    branches:
      - no_branch
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

env:
  ENVIRONMENT: dev
  
jobs:
  plan-and-deploy:
    name: Plan and deploy
    runs-on: ubuntu-latest
    environment: $ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
        with:
          # Todo: Don't hardcode branch
          ref: main
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_arn }}
          aws-region: eu-west-2
          
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">=1.5.0"
          
      - name: Terraform init
        run: terraform init -backend-config=tfvars/$ENVIRONMENT-backend.tfvars
        
      # - name: Terraform validate
      #   run: terraform validate
        
      # name: Terraform plan
      # env:
      #   TF_VAR_ecr_repository_url: ${{ secrets.registry_url }}
      #   TF_VAR_backoffice_ecr_repository_name: ${{ secrets.backoffice_repository_name }}
      #   TF_VAR_webapp_ecr_repository_name: ${{ secrets.webapp_repository_name }}
      #   # Todo: Deal with hardcoded image tag
      #   TF_VAR_image_tag: 4f44945cad38927702a07e926733e4bd126c7f54
      #   TF_VAR_aws_account_number: ${{ secrets.aws_account_number }}
      #   TF_VAR_db_username: ${{ secrets.db_username }}
      #   TF_VAR_db_password: ${{ secrets.db_password }}
      #   TF_VAR_alert_email_address: ${{secrets.alert_email_address}}
      #   TF_VAR_alert_pagerduty_integration_url: ${{ secrets.alert_pagerduty_integration_url }}
      #   TF_VAR_backoffice_environment_file: ${{ secrets.backoffice_env_file }}
      #   TF_VAR_webapp_environment_file: ${{ secrets.webapp_env_file }}
      # run: terraform plan -input=false -var-file=tfvars/$ENVIRONMENT.tfvars
